### ISSUE TITLE
Is Newtonsoft.Json (>= 12.0.2) really required?!

### ISSUE THREAD

**Issue by aburakab** [bamotav/Hangfire.RecurringJobAdmin#17]
I have a conflict between two libraries, this one require 
**Newtonsoft.Json (>= 12.0.2)**
and the other one
**Newtonsoft.Json (>= 10.0.0 && < 11.0.0)**
Since it require a DLL less than v11 may you please check if **Newtonsoft.Json >= 10.0.3** is ok.

**Comment by felixclase** [comment]
I will be checking.

But, surely it is possible to download the version of Newtonsoft.Json.

**Comment by aburakab** [comment]
Hmmm .. I just forked the project to try downgrading NewtonSoft to 10.0.3 .. it refused by another dependency ... Looks like Hangfire require 11.0.1

**Comment by aburakab** [comment]
Downgrading is possible that's true, but looks like *nuget specification
file* is limiting that, please check *.nuspec* file. and allow users to use
a lower version. By the way, i tried to downgrade it when i forked the
repo. but looks like Hangfire lib is not allowing me to go lower than 11.0.2

**Comment by bamotav** [comment]
Hi @aburakab, thanks for reporting this issue and forgive me for taking a long time to respond. I will try to downgrade the version to the same as Hangfire, but I don't know if it helps.

**Comment by Jadhielv** [comment]
I would like to help you with this @bamotav
