### ISSUE TITLE
Xml Parsing Errors When Trying to Add New Job

### ISSUE THREAD

**Issue by brendonwm** [bamotav/Hangfire.RecurringJobAdmin#18]
The endpoints called appear to return JSON but I'm seeing XML parsing errors in the browser debug console.
![image](https://user-images.githubusercontent.com/22039891/75928703-17412380-5ec3-11ea-86df-cef70b4cab7c.png)

**Comment by bamotav** [comment]
Thanks, @brendonwm for reporting it, I will try to replicate and solve it

**Comment by bamotav** [comment]
Hi @brendonwm, can you provide any screenshots showing the information you entered in the form?

I tried to replicate it but it doesn't happen to me.

**Comment by bamotav** [comment]
Hi @brendonwm, you can update I fixed a lot of issues.
