### ISSUE TITLE
Get Jobs query broken

### ISSUE THREAD

**Issue by ke-real** [bamotav/Hangfire.RecurringJobAdmin#19]
Job Configuration page does not display any jobs.

Broken by this commit https://github.com/bamotav/Hangfire.RecurringJobAdmin/commit/8f46030bfba1e5d57b4ceabaf26c018058db6eb1

file GetJobDispatcher, line 36

**Comment by bamotav** [comment]
Hi @ke-real, I solved this issue, thanks for reporting it, I included this fix to the next release.
