### ISSUE TITLE
With the new 1.7.13 version of Hangfire "The Class not found" error on Job edit

### ISSUE THREAD

**Issue by TropinAlexey** [bamotav/Hangfire.RecurringJobAdmin#25]
Hi, @bamotav . What could it be?
My installed Hangfire.RecurringJobAdmin version is 0.1.5

![Snapshot 2020-09-18 11 29 15](https://user-images.githubusercontent.com/51405410/93576849-feeaaf00-f9a3-11ea-950c-988fb6032828.png)

![Snapshot 2020-09-18 11 29 28](https://user-images.githubusercontent.com/51405410/93576237-576d7c80-f9a3-11ea-936f-be6c3aeb692d.png)

**Comment by bamotav** [comment]
Thanks, @TropinAlexey  for reporting this issue, I just did the fix and the update is now available.

**Comment by kanuw** [comment]
Hi @bamotav, when this fix will be released?
