### ISSUE TITLE
Error in datetime Next Execution and Last Execution

### ISSUE THREAD

**Issue by RonaldCast** [bamotav/Hangfire.RecurringJobAdmin#31]
Hello,
I show an issues in the columns **next execution** and **last execution**. I need your help with that.

### Description problem
The Configuration job and the datetime in Next Execution and Last Execution aren't exact. For example: In the  image, whether we see the job (id:CloseMenuForDayBreakfast) the configuration cron is  `0 8 * * 0-6`, whereby the next execution must is the **2020-09-24 8:00**, but the next execution in the column is in  **2020-09-24 12:00.**  

![image](https://user-images.githubusercontent.com/24918679/94979335-0e174400-04f0-11eb-8498-c5f9491a8be3.png)

### Extra information for help

My timezone is **_America/Santo_Domingo_**
    
```
[RecurringJob("0 8 * * 0-6", "America/Santo_Domingo", "default", RecurringJobId = "CloseMenuForDayBreakfast")]
        public async Task CloseMenuForDayBreakfast()
        {
        //body code
        }

```

I think that is the _**timezone**_ configuration of plugin that doesn't get my configuration timezone.

**Comment by bamotav** [comment]
Hi, @RonaldCast thanks for report this issue, I will fix this issue in the next release, keep waiting, please.
