### ISSUE TITLE
DisableConcurrentlyJobExecutionAttribute doesn't play nice with Failed

### ISSUE THREAD

**Issue by fernandonajera** [bamotav/Hangfire.RecurringJobAdmin#33]
I try to describe a job that should be executed every 10 minutes, shouldn't be executed if already running, and shouldn't be retried: 

```csharp
[RecurringJob("*/10 * * * *", "default", RecurringJobId = "ThisService")]
[DisableConcurrentlyJobExecution(nameof(DoThis))]
[AutomaticRetry(Attempts = 0, OnAttemptsExceeded = AttemptsExceededAction.Fail)]
public async Task DoThis(PerformContext ctx)
{
    throw new Exception();
}
```

This code always ends up *deleting* the task, instead of marking it as failed.

The reason seems to be the check at https://github.com/bamotav/Hangfire.RecurringJobAdmin/blob/master/src/Hangfire.RecurringJobAdmin/Attributes/DisableConcurrentlyJobExecutionAttribute.cs

```csharp
... && !context.CandidateState.IsFinal
```

The state Failed is not marked as IsFinal (see https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/States/FailedState.cs), so the task is deleted instead of being reported as expected.

As a workaround I'm deploying my own attribute which checks for this particular state.

**Comment by bamotav** [comment]
Thanks, @fernandonajera for reporting this problem, and for your good explanation, I replied and solved it, in the next version it will be there.

![image](https://user-images.githubusercontent.com/36558623/95035467-37240a00-0693-11eb-8899-6807bb898343.png)

In the next version we will include a new parameter for the attribute in which you can pass the state you want for when the attribute cancels the execution of the job:

![image](https://user-images.githubusercontent.com/36558623/95035750-0395af80-0694-11eb-9b41-541fc96d69cc.png)

`   public enum JobState
    {
        DeletedState,
        FailedState,
        EnqueuedState,
    }`

Note: When the job throws an exception, the status should always be Fail.
