### ISSUE TITLE
Create a new status called Jobs Stopped

### ISSUE THREAD

**Issue by bamotav** [bamotav/Hangfire.RecurringJobAdmin#36]
Create a new status called Jobs Stopped, it will show all the jobs stopped by the Job Configuration Panel:

<img width="753" alt="image" src="https://user-images.githubusercontent.com/36558623/95039518-00ec8780-069f-11eb-845e-7a0877c4c912.png">

We can get all jobs stopped from the static class `JobAgent.GetAllJobStopped `.

**Comment by Ibrahim-Islam** [comment]
I will work on this 😃

**Comment by bamotav** [comment]
Hi @Ibrahim-Islam you can guide yourself with this repository: https://github.com/raisedapp/Hangfire.JobsLogger.

**Comment by JossyDevers** [comment]
Done.

**Comment by Jadhielv** [comment]
Closes with #62 @bamotav. @JossyDevers use `Fix #issue` to linked issue with **pull request**.

**Comment by Jadhielv** [comment]
Closes with #62 @bamotav. @JossyDevers use `Fix #issue` to linked issue with **pull request**.

**Comment by bamotav** [comment]
@Ibrahim-Islam sorry but you already have more than 10 days and I could not see the fork of the project either
