### ISSUE TITLE
Add Pagination to the Recurring Jobs grid

### ISSUE THREAD

**Issue by bamotav** [bamotav/Hangfire.RecurringJobAdmin#37]
Add Pagination to the Recurring Jobs grid:

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/36558623/95039792-c505f200-069f-11eb-8881-ea61f046c3bb.png">

**Comment by hey-mikey** [comment]
Hi,

I'd like to work on this, if that's alright? 

I think I have it set up locally, but I'm not sure how to get to the JobConfiguration view. Is the Sample project supposed to be the startup project?

**Comment by JossyDevers** [comment]
> Hi,
> 
> I'd like to work on this, if that's alright?
> 
> I think I have it set up locally, but I'm not sure how to get to the JobConfiguration view. Is the Sample project supposed to be the startup project?

@hey-mikey 

When running the sample project, go to this path in the browser: https://localhost:44385/hangfire/JobConfiguration

**Comment by Jadhielv** [comment]
Closes with #56 @bamotav
