### ISSUE TITLE
Changes the label buttons actions to icons

### ISSUE THREAD

**Issue by bamotav** [bamotav/Hangfire.RecurringJobAdmin#38]
Changes the labels buttons actions to icons:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/36558623/95039925-2037e480-06a0-11eb-8575-a97e66f2f522.png">

For example:

1. Label Start to icon play
2. Label Stop to icon stop.

![image](https://user-images.githubusercontent.com/36558623/95040035-802e8b00-06a0-11eb-84d6-e30c4681f4e9.png)

![image](https://user-images.githubusercontent.com/36558623/95040056-8fadd400-06a0-11eb-8964-a84bc9ccfdd0.png)

**Comment by oxavibes** [comment]
I would like to help you with this

**Comment by bamotav** [comment]
Thanks @oxavibes I assigned it to you.

**Comment by oxavibes** [comment]
Hi @bamotav. Can you guide me with the installation process? Which are the steps to follow? I just installed .NET CORE 3.1 and ran "dotnet run" with no success. Do I need to install anything else? I am not familiar with .NET development. Thanks

**Comment by bamotav** [comment]
Hi @oxavibes , forgive me soon I will have to update the readme so that I have the contribution guide, but you need to install the SDK 2.2 :

<img width="373" alt="image" src="https://user-images.githubusercontent.com/36558623/95123002-4fda0180-071f-11eb-9301-7e62647f5794.png">

Link: https://dotnet.microsoft.com/download/dotnet-core/2.2

Later you can work with differents IDE or Editor : Visual Studio, Visual Studio Code, etc..

If you use Visual Studio code open the integrate terminal in the sample project: 

<img width="394" alt="image" src="https://user-images.githubusercontent.com/36558623/95123520-16ee5c80-0720-11eb-9707-4060be100abd.png">

run `dotnet build` check if everything compiled fine and then `dotnet run`
