### ISSUE TITLE
Use moment js for the dates columns

### ISSUE THREAD

**Issue by bamotav** [bamotav/Hangfire.RecurringJobAdmin#39]
Use moment js for the dates columns of grids.

The idea is are values of the columns say like that the grid original of recurrings jobs grid:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/36558623/95040293-36927000-06a1-11eb-8707-845c778110d1.png">

The original grid uses a razor server-side to render this value in the columns but you need to replicate this logic on the client-side using Vuejs.

You can check the file HtmlHelper:

<img width="385" alt="image" src="https://user-images.githubusercontent.com/36558623/95040473-bd474d00-06a1-11eb-85cf-80761af9dd9e.png">

The path: https://github.com/HangfireIO/Hangfire/blob/14a8c4207bb3bf6ca8cb5823b32729c66a91459a/src/Hangfire.Core/Dashboard/HtmlHelper.cs

For injecting another external library:

1- Add the file to the folder:

![image](https://user-images.githubusercontent.com/36558623/95040596-24650180-06a2-11eb-9289-0d1433a88630.png)

2- Right-click the file and select the options property and changes build action to Embedded resource and the second option in the same display changes to Copy always :

<img width="456" alt="image" src="https://user-images.githubusercontent.com/36558623/95040721-7e65c700-06a2-11eb-87af-e9201149aadb.png">

3: Add the resources to the Dashboard route:

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/36558623/95040795-c1279f00-06a2-11eb-8810-7ee1a6808fd9.png">

**Comment by bcwood** [comment]
Development on moment.js has effectively stopped, so you may want to consider other options.

https://momentjs.com/docs/#/-project-status/

> In most cases, you should not choose Moment for new projects.

**Comment by bamotav** [comment]
Thanks, @bcwood I was unaware of this, I will have to find another way.
