### ISSUE TITLE
Concurrency issue with Hangfire.RecurringJobAdmin.PeriodicJobBuilder.GetAllJobs()

### ISSUE THREAD

**Issue by geoffreytran** [bamotav/Hangfire.RecurringJobAdmin#42]
I am running into an issue with Xunit tests that are ran in parallel using the WebApplicationFactory. As the Startup is instantiated in parallel (4 threads concurrent), the PeriodicJobBuilder.GetAllJobs() method is running into concurrency issues with the assignment of the Metadata property.

System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Hangfire.RecurringJobAdmin.PeriodicJobBuilder.GetAllJobs()
   at Hangfire.RecurringJobAdmin.ConfigurationExtensions.UseRecurringJobAdmin(IGlobalConfiguration config, Assembly[] assemblies)

PeriodicJobBuilder.Metadata = new List<RecurringJobAttribute>(); // I assume that if we change to use a temporary variable and make the assignment to the Metadata property at the end of the GetAllJobs method, the concurrency issues would be mitigated?

`
  internal static class PeriodicJobBuilder
  {
    public static List<RecurringJobAttribute> Metadata { get; private set; }

    internal static void GetAllJobs()
    {
      PeriodicJobBuilder.Metadata = new List<RecurringJobAttribute>();
      foreach (Assembly assembly in StorageAssemblySingleton.GetInstance().currentAssembly)
      {
        foreach (Type type in assembly.GetTypes())
        {
          foreach (MethodInfo declaredMethod in type.GetTypeInfo().DeclaredMethods)
          {
            if (declaredMethod.IsDefined(typeof (RecurringJobAttribute), false))
            {
              RecurringJobAttribute customAttribute = declaredMethod.GetCustomAttribute<RecurringJobAttribute>(false);
              if (customAttribute != null)
              {
                if (declaredMethod.GetCustomAttributes(true).OfType<RecurringJobAttribute>().Any<RecurringJobAttribute>())
                  PeriodicJobBuilder.Metadata.Add(declaredMethod.GetCustomAttribute<RecurringJobAttribute>());
                new RecurringJobRegistry().Register(customAttribute.RecurringJobId, declaredMethod, customAttribute.Cron, string.IsNullOrEmpty(customAttribute.TimeZone) ? TimeZoneInfo.Utc : TimeZoneInfo.FindSystemTimeZoneById(customAttribute.TimeZone), customAttribute.Queue ?? "default");
              }
            }
          }
        }
      }
    }
`

**Comment by bamotav** [comment]
Hi @geoffreytran, thanks for reporting this issue, I think it's better to remove this property because I never use it, I guess I created it in the past to use it for something specific but right now I can see that I'm not using it.

Do you think that if I remove the property your problem will be solved?

Anyway I have a PR pending to clean the code in that will be the solution to your problem.

**Comment by Jadhielv** [comment]
I would like to help you with this @bamotav

**Comment by geoffreytran** [comment]
Looking closer, it looks like that property has been there since the previous releases. It may not be the root cause of the issue. I am not sure at the moment which collection is enumerated and modified at the same time, I'll try to find a consistent way to reproduce the error.
