### ISSUE TITLE
Add new job "Class not found" error

### ISSUE THREAD

**Issue by TropinAlexey** [bamotav/Hangfire.RecurringJobAdmin#63]
Hi, @bamotav 
I have this issue again with 1.0.0 RecurringJobAdmin and 1.7.17 Hangfire versions installed. Doesn't matter what class name I'm putting: full path or not.
In addition to that any error is forcing to add all job parameters again. This is really annoying behavior, could you fix it?
Thank you in advance

![Job Configuration – Hangfire Dashboard - Vivaldi 1](https://user-images.githubusercontent.com/51405410/97179450-82689e80-17a1-11eb-83f2-b36bd30ad50f.png)
![Job Configuration – Hangfire Dashboard - Vivaldi 2](https://user-images.githubusercontent.com/51405410/97179467-85638f00-17a1-11eb-9898-b9bc6a2a9596.png)

**Comment by bamotav** [comment]
Hi @TropinAlexey, could you try with the full path that is the name of the solution and the name of the class?

Like this:
![image](https://user-images.githubusercontent.com/36558623/97205150-74a91e00-178d-11eb-98f7-1210cc675039.png)

In the new version including this new parameter (`includeReferences`) which includes the Dlls referenced to the project: 

![image](https://user-images.githubusercontent.com/36558623/97205656-1e88aa80-178e-11eb-8144-3397c69805dd.png)

**Comment by TropinAlexey** [comment]
Thank you, @bamotav 
.UseRecurringJobAdmin(**true**, typeof(Startup).Assembly);
in startup.cs is fixed my problem
