### ISSUE TITLE
Job configuration page layout and JS issue in Chrome

### ISSUE THREAD

**Issue by alexandis** [bamotav/Hangfire.RecurringJobAdmin#78]
Here's how the page looks like here:

![image](https://user-images.githubusercontent.com/6149843/102344318-649b0700-3fa4-11eb-9727-c08d29d84975.png)

The error while trying to parse dates is:

> vue:6 TypeError: Cannot read property 'length' of null
>     at wn.eval (eval at Ya (vue:6), <anonymous>:3:3901)
>     at wn.e._render (vue:6)
>     at wn.r (vue:6)
>     at fn.get (vue:6)
>     at new fn (vue:6)
>     at vue:6
>     at wn.$mount (vue:6)
>     at wn.$mount (vue:6)
>     at wn.t._init (vue:6)
>     at new wn (vue:6)

**Comment by cocoon** [comment]
Caused by this:

https://github.com/bamotav/Hangfire.RecurringJobAdmin/blob/master/src/Hangfire.RecurringJobAdmin/Dashboard/Content/css/JobExtension.css#L4

**Comment by marcoCasamento** [comment]
I've got the same problem and it seems that the fix can solve it

**Comment by LucasBLs** [comment]
I also have the same problem.

**Comment by AlexTokar** [comment]
The issue returned back. The same view, the same error, and the same problem
